### ISSUE TITLE
 Bticino F20T60A (Legrand 412015) Invalid Image Update OTA

### ISSUE THREAD

**Issue by Steve707-AE** [Koenkk/zigbee-OTA#356] opened 2023-09-11 22:17 UTC
Today I received the update version 5325315 and the current installed version is 5129215. This version shows in the log but in the UI it says versione 004e. When I push on update after 10 seconds appear a popup saying invalid image. I attach a screenshot below

![screenshot](https://github.com/Koenkk/zigbee-OTA/assets/72551650/3401775b-7783-47ca-931c-7988f07d7398)

What could it be the solution?

**Comment by pierrepinon** [comment] 2023-09-13 08:06
An issue is already open for this #328

**Comment by Koenkk** [comment] 2023-09-13 17:46
Duplicate of https://github.com/Koenkk/zigbee-OTA/issues/328 indeed.

**Closed by Koenkk** 2023-09-13 17:46 UTC
